Launchx integration - Login Client
Nota-NetsPresso/netspresso-python pull request #17
Opened 2023-07-28 07:01 UTC by SanggeonPark

우선 Login Client만 공용으로 사용하는 형태를 만들어보았습니다.
확인해보시고 알려주세요~

그리고 Merge는 나중에 실제로 LaunchX integration 되면 하겠습니다.

2023-07-31 04:43 UTC, paran3 commented on netspresso/client/config.py
> +class EnvironmenType(str, Enum):
@SanggeonPark 님 오타가 있는것 같습니다.

2023-07-31 05:23 UTC, paran3 commented
@SanggeonPark @Only-bottle 
혹시 PyNP 레포에 모든 기능을 테스트 할 수 있는 코드가 작성되어 있을까요?

2023-07-31 05:36 UTC, SanggeonPark commented on netspresso/client/config.py
> +class EnvironmenType(str, Enum):
넵 확인했습니다! 고마와요!

2023-07-31 05:37 UTC, SanggeonPark commented
> @SanggeonPark @Only-bottle 혹시 PyNP 레포에 모든 기능을 테스트 할 수 있는 코드가 작성되어 있을까요?

저는 examples 폴더 아래에 있는 코드를 모두 돌려보고 있어요~

2023-07-31 08:29 UTC, Only-bottle commented
> @SanggeonPark @Only-bottle 혹시 PyNP 레포에 모든 기능을 테스트 할 수 있는 코드가 작성되어 있을까요?

아직은 test 코드를 만들어두진 못했습니다. 상건님 말씀처럼 예제 코드정도로만 확인해보고 있어요. ㅠㅠ
test 코드도 얼른 붙혀야 할 거 같아요

2023-08-01 05:55 UTC, Only-bottle commented on netspresso/__init__.py
> +__version__ = "1.0.6"
해당 버전 수정은 나중에 vit 옵션 추가한 부분까지 합치고 나서 수정하는 게 어떨까요? (LaunchX랑 ViT 지원을 같이 하기 때문)
현재 버전 수정하는 시점은 pypi에 업로드 하는 기준이라서요.

2023-08-02 01:52 UTC, Only-bottle commented on netspresso/compressor/__init__.py
> +    def __init__(self, *args, **kwargs):
혹시 이 부분 email, password에서 *args, **kwargs 으로 변경하신 이유가 있으실까요?

2023-08-02 23:21 UTC, paran3 commented on netspresso/schemas/auth.py
> +class UserResponese(BaseModel):
@SanggeonPark 오타가 있습ㄴ디ㅏ.

2023-08-03 00:46 UTC, SanggeonPark commented on netspresso/__init__.py
> +__version__ = "1.0.6"
넵넵!! 그럴게요!

2023-08-03 00:48 UTC, SanggeonPark commented on netspresso/compressor/__init__.py
> +    def __init__(self, *args, **kwargs):
아래 두가지 경우를 모두 커버하게 하기 위해서요~
```
compressor = ModelCompressor(email="sanggeon.park@nota.ai", password="jwuatxbh")
compressor = ModelCompressor(SessionClient(email="sanggeon.park@nota.ai", password="jwuatxbh"))
```

2023-08-03 00:52 UTC, SanggeonPark commented on netspresso/schemas/auth.py
> +class UserResponese(BaseModel):
고마와요!

2023-08-03 02:28 UTC, Only-bottle commented on netspresso/compressor/__init__.py
> +    def __init__(self, *args, **kwargs):
2번째 경우를 사용하는 일이 언제일까요?
그럼 유저는 두 가지 방법으로 Model Compressor를 사용하는 거라고 생각하면 될까요?

2023-08-03 08:29 UTC, Youngwhy requested changes

2023-08-03 08:29 UTC, Youngwhy commented on netspresso/client/__init__.py
> +class BaseClient:
argument를 받을 수 있는 경우가 두가지(1. email/password, 2.user_session) 경우만 있으므로 아래와 같이 만들면 조금 더 간단할 것 같아서 제안드립니다.
```
class BaseClient:
    def __init__(self, email=None, password=None, user_session=None):
        if user_session:
            # Case 1: Creating from a user_session
            self._init_from_session(user_session)
        elif email and password:
            # Case 2: Creating from email and password
            self.email = email
            self.password = password
        else:
            raise NotImplementedError("There is no avaliable constructors for given paremeters.")

    def _init_from_session(self, user_session):
        self.user_session = user_session
```

2023-08-04 02:50 UTC, SanggeonPark commented on netspresso/client/__init__.py
> +class BaseClient:
변경하였습니다~

2023-08-07 08:36 UTC, merged