Add convert (TFLite int8) and benchmark for Alif Ensemble DevKit Gen2 and Renesas RA8D1
Nota-NetsPresso/netspresso-python pull request #52
Opened 2023-11-08 09:54 UTC by Only-bottle

## Description

Please include a summary in English, of the changes in this pull request. If it closes an issue, please mention it here.

Closes: #51 

You should link at least one existing issue for PR. Before your create a PR, please check to see if there is an issue for this change.  
PRs from forked repository not accepted.

## Change(s)

- Add int8 data type for TFLite converting
- Add Alif Ensemble DevKit Gen2 adn Renesas RA8D1 on target devices

2023-11-08 11:03 UTC, SanggeonPark requested changes

2023-11-08 11:03 UTC, SanggeonPark commented on netspresso/launcher/__init__.py
> +
이렇게 함수 안에 리스트를 만들어도 좋고 어딘가 정의해서 가져다 쓰는 것도 좋을 것 같아요~
```
int8_only_device_names =  [DeviceName.ENSEMBLE_E7_DEVKIT_GEN2, DeviceName.RENESAS_RA8D1]
if data_type is DataType.INT8:
    if target_device_name not in int8_only_device_names:
         raise Exception(f"int8 converting supports only {int8_only_device_names}.")
    else:  # FP16, FP32
        if target_device_name in int8_only_device_names:
            raise Exception(f"{int8_only_device_names} only support int8 data types.")
```

2023-11-08 11:03 UTC, SanggeonPark commented on netspresso/launcher/__init__.py
> +            # Check available int8 converting devices
여기 리스트도
```
[DeviceName.ENSEMBLE_E7_DEVKIT_GEN2, DeviceName.RENESAS_RA8D1]
``` 
미리 정의 해둔 것을 가져다 쓰면 좋겠어요

2023-11-08 11:03 UTC, SanggeonPark commented on netspresso/launcher/utils/devices.py
> +
filter_devices_with_hardware_type 이라는 함수도 필요치 않을까요?

2023-11-08 11:03 UTC, SanggeonPark commented on netspresso/launcher/__init__.py
>              devices = filter_devices_with_device_name(name=target_device_name, devices=model.available_devices)
여기서 hardware_type이 있는 경우 filter가 된 devices에서 다시 한번 hardware_type으로 필터를 해야할겁니다.

2023-11-08 11:04 UTC, Only-bottle commented on netspresso/launcher/__init__.py
> +
넵 해당 부분 반영하겠습니다~

2023-11-08 11:05 UTC, Only-bottle commented on netspresso/launcher/__init__.py
> +            # Check available int8 converting devices
넵 위 내용이랑 같다고 생각하네요 같이 반영하겠습니다~

2023-11-08 11:05 UTC, Only-bottle commented on netspresso/launcher/__init__.py
>              devices = filter_devices_with_device_name(name=target_device_name, devices=model.available_devices)
안 그래도 고민이였는데 위에 말씀하신 함수 추가후 필터링하는 것으로 하겠습니다.

2023-11-09 12:25 UTC, SanggeonPark approved these changes

2023-11-21 05:18 UTC, merged